# Generated by Django 5.2.7 on 2025-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='RegistrationNo',
            new_name='IDNo',
        ),
    ]
